export const LOAD_BOXES_SUCCESS = "LOAD_BOXES_SUCCESS";
export const CREATE_BOX_SUCCESS = "CREATE_BOX_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
